/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({
  'survivalTime' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Text,
  'survivalTime' : IDL.Nat,
  'kills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getPlayerScore' : IDL.Func([], [IDL.Opt(Score)], ['query']),
  'getTopLeaderboardEntries' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'saveScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({ 'survivalTime' : IDL.Nat, 'kills' : IDL.Nat });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Text,
    'survivalTime' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  
  return IDL.Service({
    'getPlayerScore' : IDL.Func([], [IDL.Opt(Score)], ['query']),
    'getTopLeaderboardEntries' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'saveScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };